import os
import json

from dotenv import load_dotenv


load_dotenv()

CWM_MINIO_API_HOST = os.getenv("CWM_MINIO_API_HOST")
CWM_MINIO_API_USERNAME = os.getenv("CWM_MINIO_API_USERNAME")
CWM_MINIO_API_PASSWORD = os.getenv("CWM_MINIO_API_PASSWORD")

CWM_INSTANCE_ID = os.getenv("CWM_INSTANCE_ID")
CWM_INSTANCE_ACCESS_KEY = os.getenv("CWM_INSTANCE_ACCESS_KEY")
CWM_INSTANCE_SECRET_KEY = os.getenv("CWM_INSTANCE_SECRET_KEY")

CWM_KEEP_INSTANCE = os.getenv("CWM_KEEP_INSTANCE", "").lower() == "yes"
CWM_KEEP_BUCKETS = os.getenv("CWM_KEEP_BUCKETS", "").lower() == "yes"

CWM_UPLOADER_DOWNLOADER_ENABLED = os.getenv("CWM_UPLOADER_DOWNLOADER_ENABLED", "no").lower() == "yes"
CWM_UPLOADER_DOWNLOADER_UPLOAD_WEIGHT = int(os.getenv("CWM_UPLOADER_DOWNLOADER_UPLOAD_WEIGHT", "1"))
CWM_UPLOADER_DOWNLOADER_DOWNLOAD_WEIGHT = int(os.getenv("CWM_UPLOADER_DOWNLOADER_DOWNLOAD_WEIGHT", "100000"))
CWM_UPLOADER_DOWNLOADER_PUBLIC_WEIGHT = int(os.getenv("CWM_UPLOADER_DOWNLOADER_PUBLIC_WEIGHT", "1"))
CWM_UPLOADER_DOWNLOADER_PRIVATE_WEIGHT = int(os.getenv("CWM_UPLOADER_DOWNLOADER_PRIVATE_WEIGHT", "1"))
CWM_UPLOADER_DOWNLOADER_CONTENT_LENGTH_VALUES = os.getenv("CWM_UPLOADER_DOWNLOADER_CONTENT_LENGTH_VALUES", "5,1024,1048576")
CWM_UPLOADER_DOWNLOADER_CONTENT_LENGTH_VALUES = [int(x.strip()) for x in CWM_UPLOADER_DOWNLOADER_CONTENT_LENGTH_VALUES.split(",") if x.strip()]
CWM_UPLOADER_DOWNLOADER_CONTENT_LENGTH_WEIGHTS = os.getenv("CWM_UPLOADER_DOWNLOADER_CONTENT_LENGTH_WEIGHTS", "100,10,1")
CWM_UPLOADER_DOWNLOADER_CONTENT_LENGTH_WEIGHTS = [int(x.strip()) for x in CWM_UPLOADER_DOWNLOADER_CONTENT_LENGTH_WEIGHTS.split(",") if x.strip()]
CWM_UPLOADER_DOWNLOADER_MAX_FILES_PER_BUCKET = int(os.getenv("CWM_UPLOADER_DOWNLOADER_MAX_FILES_PER_BUCKET", "1000"))

CWM_GETGETTER_ENABLED = os.getenv("CWM_GETGETTER_ENABLED", "no").lower() == "yes"
