import os
import json

from dotenv import load_dotenv


load_dotenv()


CWM_MINIO_API_URL = os.getenv("CWM_MINIO_API_URL").rstrip('/')
CWM_MINIO_API_USERNAME = os.getenv("CWM_MINIO_API_USERNAME")
CWM_MINIO_API_PASSWORD = os.getenv("CWM_MINIO_API_PASSWORD")

CWM_INSTANCE_ID = os.getenv("CWM_INSTANCE_ID")
CWM_INSTANCE_ACCESS_KEY = os.getenv("CWM_INSTANCE_ACCESS_KEY")
CWM_INSTANCE_SECRET_KEY = os.getenv("CWM_INSTANCE_SECRET_KEY")
CWM_INSTANCE_BUCKET_CREDENTIALS_JSON = os.getenv("CWM_INSTANCE_BUCKET_CREDENTIALS_JSON")
if CWM_INSTANCE_BUCKET_CREDENTIALS_JSON:
    CWM_INSTANCE_BUCKET_CREDENTIALS = json.loads(CWM_INSTANCE_BUCKET_CREDENTIALS_JSON)
else:
    CWM_INSTANCE_BUCKET_CREDENTIALS = {}
