import os

from dotenv import load_dotenv


load_dotenv()

CWM_LOAD_TESTS_DEBUG = os.getenv("CWM_LOAD_TESTS_DEBUG", "no").lower() == "yes"

CWM_MINIO_API_HOST = os.getenv("CWM_MINIO_API_HOST")
CWM_MINIO_API_USERNAME = os.getenv("CWM_MINIO_API_USERNAME")
CWM_MINIO_API_PASSWORD = os.getenv("CWM_MINIO_API_PASSWORD")

CWM_INSTANCE_ID = os.getenv("CWM_INSTANCE_ID")
CWM_INSTANCE_ACCESS_KEY = os.getenv("CWM_INSTANCE_ACCESS_KEY")
CWM_INSTANCE_SECRET_KEY = os.getenv("CWM_INSTANCE_SECRET_KEY")

CWM_INIT_FROM_REDIS = os.getenv("CWM_INIT_FROM_REDIS", "").lower() == "yes"
CWM_KEEP_INSTANCE = os.getenv("CWM_KEEP_INSTANCE", "").lower() == "yes"
CWM_KEEP_BUCKETS = os.getenv("CWM_KEEP_BUCKETS", "").lower() == "yes"
CWM_KEEP_REDIS_DATA = os.getenv("CWM_KEEP_REDIS_DATA", "").lower() == "yes"

# waits for all updowndel users to finish on_start and then stops them and starts getgetter users
# this only works if: there is more than one user type enabled, including updowndel, and updowndel has fixed_count
CWM_UPDOWNDEL_SEPARATE_FROM_OTHER_USERS = os.getenv("CWM_UPDOWNDEL_SEPARATE_FROM_OTHER_USERS", "no").lower() == "yes"
CWM_UPDOWNDEL_ENABLED = os.getenv("CWM_UPDOWNDEL_ENABLED", "yes").lower() == "yes"
CWM_UPDOWNDEL_USER_WEIGHT = int(os.getenv("CWM_UPDOWNDEL_USER_WEIGHT", "1"))
CWM_UPDOWNDEL_FIXED_COUNT = int(os.getenv("CWM_UPDOWNDEL_FIXED_COUNT", "0"))
CWM_UPDOWNDEL_UPLOAD_WEIGHT = int(os.getenv("CWM_UPDOWNDEL_UPLOAD_WEIGHT", "1"))
CWM_UPDOWNDEL_DOWNLOAD_WEIGHT = int(os.getenv("CWM_UPDOWNDEL_DOWNLOAD_WEIGHT", "1"))
CWM_UPDOWNDEL_DELETE_WEIGHT = int(os.getenv("CWM_UPDOWNDEL_DELETE_WEIGHT", "1"))
CWM_UPDOWNDEL_PUBLIC_WEIGHT = int(os.getenv("CWM_UPDOWNDEL_PUBLIC_WEIGHT", "1"))
CWM_UPDOWNDEL_PRIVATE_WEIGHT = int(os.getenv("CWM_UPDOWNDEL_PRIVATE_WEIGHT", "1"))
CWM_UPDOWNDEL_CONTENT_LENGTH_VALUES = os.getenv("CWM_UPDOWNDEL_CONTENT_LENGTH_VALUES", "5,1024,1048576")
CWM_UPDOWNDEL_CONTENT_LENGTH_VALUES = [int(x.strip()) for x in CWM_UPDOWNDEL_CONTENT_LENGTH_VALUES.split(",") if x.strip()]
CWM_UPDOWNDEL_CONTENT_LENGTH_WEIGHTS = os.getenv("CWM_UPDOWNDEL_CONTENT_LENGTH_WEIGHTS", "100,10,1")
CWM_UPDOWNDEL_CONTENT_LENGTH_WEIGHTS = [int(x.strip()) for x in CWM_UPDOWNDEL_CONTENT_LENGTH_WEIGHTS.split(",") if x.strip()]
CWM_UPDOWNDEL_MAX_FILES_PER_BUCKET = int(os.getenv("CWM_UPDOWNDEL_MAX_FILES_PER_BUCKET", "10"))
CWM_UPDOWNDEL_MIN_FILES_PER_BUCKET = int(os.getenv("CWM_UPDOWNDEL_MIN_FILES_PER_BUCKET", "5"))
CWM_UPDOWNDEL_CONCURRENCY = int(os.getenv("CWM_UPDOWNDEL_CONCURRENCY", "10"))
CWM_UPDOWNDEL_ON_START_NUM_BUCKETS = int(os.getenv("CWM_UPDOWNDEL_ON_START_NUM_BUCKETS", "2"))
CWM_UPDOWNDEL_ON_START_NUM_FILES_PER_BUCKET = int(os.getenv("CWM_UPDOWNDEL_ON_START_NUM_FILES_PER_BUCKET", "3"))

CWM_GETGETTER_ENABLED = os.getenv("CWM_GETGETTER_ENABLED", "yes").lower() == "yes"
CWM_GETGETTER_USER_WEIGHT = int(os.getenv("CWM_GETGETTER_USER_WEIGHT", "1"))
CWM_GETGETTER_FIXED_COUNT = int(os.getenv("CWM_GETGETTER_FIXED_COUNT", "0"))
CWM_GETGETTER_CONCURRENCY = int(os.getenv("CWM_GETGETTER_CONCURRENCY", "10"))

SHARED_STATE_REDIS_HOST = os.getenv("SHARED_STATE_REDIS_HOST", "localhost")
SHARED_STATE_REDIS_PORT = int(os.getenv("SHARED_STATE_REDIS_PORT", "6379"))
