name: CI
on:
  push:
    branches:
      - main
env:
  IMAGE: ghcr.io/cloudwebmanage/cwm-minio-api
  # these should match the versions in Dockerfile
  UV_VERSION: 0.8.8
  MIGRATE_VERSION: v4.18.3
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}
      - name: install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/${MIGRATE_VERSION}/migrate.linux-amd64.tar.gz | tar xvz &&\
          mv migrate /usr/local/bin/migrate &&\
          chmod +x /usr/local/bin/migrate
      - name: run tests
        run: |
          docker compose up -d db
          uv sync
          uv run pytest
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache-latest
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache-latest,mode=max
          build-args: |
            VERSION=${{ github.sha }}
